= Mein Arbeitstagebuch zur Reflexion
:page-pdf-download: true
:icons: font
:table-grid: none
:table-frame: ends
:table-stripes: even

Bearbeitet durch: Jasjot Singh

E-Mail: jasjot.singh@students.fhnw.ch

'''
== Do's
NOTE: Jeden Abend kurze Notizen schreiben, welche man später noch ausformulieren kann. Commit&Push every day.

== Dont's
IMPORTANT: KI die Reflexion schreiben lassen.

'''

=== Was habe ich heute gemacht?

Heute habe ich die Calc aufgabe gelöst. Ich habe mit der Aufräum Checkliste den code angeschaut und währendssen Fehler gefunden. Diese habe ich das in der Test klassen getestet und bestätigt das es fehler waren. Danach habe ich die fehler gelöst.

=== Spass gemacht hat?

Es war mal Interessant nur aufzuräumen ohne direkt die logik zu ändern. Wie zum Beispiel bei secondNumber/firstNumber sah ich direkt den Fehler aber ich konnte es noch nicht fixen. Da ich es erst mit ein test beweisen ,usste das es falsch ist und danach verbessern.

=== Mühsam war?

Nicht direkt Fehler bzw. Logik korrigieren.

=== Was ich noch Anschauen will




'''
Hier nochmals die Links zu den Aufgaben, so kann man die Reflexion gleich mit den Aufgaben verknüpfen:

link:./aufgaben/src/casualtime/index.adoc[casualtime - Casual Time]

link:./aufgaben/src/wordwrap/index.adoc[wordwrap - Automatischer Zeilenumbruch]

link:./aufgaben/src/morse/index.adoc[morse - Morsecode]

link:./aufgaben/src/datetime/index.adoc[datetime - Datumsangaben und Uhrzeiten formatieren]

link:./aufgaben/src/calc/index.adoc[calc - Calculator: Code aufräumen und debuggen]

und die Refactoring Aufgaben:
link:./refactoring/src/index.adoc[Refactorings]

