= Mein Arbeitstagebuch zur Reflexion
:page-pdf-download: true
:icons: font
:table-grid: none
:table-frame: ends
:table-stripes: even

Bearbeitet durch: Jasjot Singh

E-Mail: jasjot.singh@students.fhnw.ch

'''
== Do's
NOTE: Jeden Abend kurze Notizen schreiben, welche man später noch ausformulieren kann. Commit&Push every day.

== Dont's
IMPORTANT: KI die Reflexion schreiben lassen.

'''

=== Was habe ich heute gemacht?

Heute habe ich die Calc aufgabe gelöst. Ich habe mit der Aufräum Checkliste den code angeschaut und währendssen Fehler gefunden. Diese habe ich das in der Test klassen getestet und bestätigt das es fehler waren. Danach habe ich die fehler gelöst.

Bei CasualTime habe ich eine normale Uhrzeit HH:MM in eine sprachliche Uhrzeit umgewandelt. Ich habe Tests für Fälle wie quarter past oder quarter to geschrieben und diese dann mit if-Statements gelöst. Nachdem alle Tests grün waren, habe ich noch ein Refactoring gemacht.

Bei der DateTime Aufgabe musste ich Text mit Elementen in formatierten Casual- und Formal-Text umwandeln. Mit dem Interface und den Klassen Formal und Casual konnte ich im TextFormatter Datum und Uhrzeit erkennen und formatieren. Dabei habe ich mit Scanner gearbeitet und Tests für die verschiedenen Fälle Casual / Formal geschrieben.

Bei der Morse Aufgabe habe ich einen Binärbaum mit der Klasse MorseNode erstellt. Danach bin ich je nach Punkt oder Strich durch den Baum gegangen und habe den Text als String ausgegeben.

Bei der WordWrap Aufgabe musste ich einen Konstruktor und die dazugehörige wrap Methode implementieren, sodass man durch eine maximale Anzahl Zeichen in einer Zeile automatisch Umbrüche erstellt.

Ich habe die Refactoring-Aufgaben ToDo und TicTacToe gemacht. Bei der ToDo-Aufgabe musste ich verschiedene Methoden und Variablen extrahieren und in eine neue Klasse verschieben. Bei TicTacToe war das Ganze etwas aufwendiger. Dort habe ich die Spiellogik von der GUI getrennt und in eigene Klassen ausgelagert. Dabei habe ich verschiedene Refactoring-Funktionen von IntelliJ benutzt, zum Beispiel Extract Method und Move. Am Schluss habe ich für die Spiellogik noch Unit-Tests geschrieben. Dabei habe ich auch die richtige art des commitens benutzt.

=== Spass gemacht hat?

Es war mal interessant, nur aufzuräumen, ohne direkt die Logik zu ändern. Wie zum Beispiel bei secondNumber/firstNumber sah ich direkt den Fehler, aber ich konnte ihn noch nicht fixen. Da ich erst mit einem Test beweisen musste, dass es falsch ist und es danach verbessern konnte.

Bei CasualTime war es sehr spannend, wieder mal so viele if-Statements zu erstellen und diese nochmals zu refactoren.

Bei der DateTime Aufgabe war es interessant, mal wieder zu sehen, wie nützlich so ein Interface sein kann. Auch das Formatieren von dem Text war spannend zu machen und zu testen.

Es hat Spass gemacht, den Baum mit den verschiedenen Punkt- und Strich-Kombinationen zu erstellen. Es war interessant, das mal wieder im Code zu erstellen, weil ich die Theorie schon im Unterricht durchgenommen habe.

s war interessant, durch vorhandenen Code in der adoc Datei die Methode und den Konstruktor zu erstellen. Ich musste zuerst überlegen, wie ich vorgehen soll und welche Tests ich schreiben muss.

Es war sehr interessant, die Refactoring-Funktionen zu benutzen. Ich muss sagen, dass ich diese bis jetzt fast nie benutzt habe. Deshalb hat mir die Aufgabe geholfen, mich in diesem Bereich zu verbessern. Es war spannend zu sehen, wie man Methoden extrahieren oder verschieben kann und IntelliJ die betroffenen Stellen automatisch anpasst.

=== Mühsam war?

Nicht direkt Fehler bzw. Logik korrigieren.

Bei CasualTime war es ein wenig komplex, da ich viele if-Statements und auch if-else gebraucht habe.

Bei DateTime war es am Anfang noch schwierig, die ganzen Zusammenhänge zu verstehen.

Sehr viel wiederholung beim schreiben des Baumes.

Bei der WordWrap Aufgabe war es mühsam, sich Tests zu überlegen und zu schauen, ob man alle Fälle abgedeckt hat.

Beim Refactoring musste man genau schauen, was man wohin verschiebt. Vor allem wenn eine Methode viele Verbindungen zu anderen Methoden oder Variablen hatte, entstanden beim Verschieben mehrere Stellen, die danach noch angepasst werden mussten. Das war bei TicTacToe teilweise etwas mühsam.
=== Was ich noch Anschauen will

Ich werde sicher später wieder mal solche Checklisten benutzen oder eventuell selber eine erstellen.

Ich werde nochmals genauer anschauen, welche Vorteile Interfaces haben können.

Schleifen waren für mich schon immer ein interessantes, aber auch schwieriges Thema. Das werde ich weiterhin anschauen.

Refactoring ist sicher ein Thema, das ich mir noch genauer anschauen möchte, weil ich die Refactoring-Funktionen von IntelliJ bis jetzt im Studium eigentlich kaum benutzt habe. Ich möchte vor allem noch besser verstehen, wann welches Refactoring sinnvoll ist.


'''
Hier nochmals die Links zu den Aufgaben, so kann man die Reflexion gleich mit den Aufgaben verknüpfen:

link:./aufgaben/src/casualtime/index.adoc[casualtime - Casual Time]

link:./aufgaben/src/wordwrap/index.adoc[wordwrap - Automatischer Zeilenumbruch]

link:./aufgaben/src/morse/index.adoc[morse - Morsecode]

link:./aufgaben/src/datetime/index.adoc[datetime - Datumsangaben und Uhrzeiten formatieren]

link:./aufgaben/src/calc/index.adoc[calc - Calculator: Code aufräumen und debuggen]

und die Refactoring Aufgaben:
link:./refactoring/src/index.adoc[Refactorings]

